### ISSUE TITLE
Add a LICENSE for this project

### ISSUE THREAD

**Issue by jfillo** [CRC-Mismatch/opentelemetry-auto-redis#2]
This project is missing a license file. Can you add one so that people know how it can be used as a dependency in their own projects?

For reference, the https://github.com/open-telemetry/opentelemetry-php-contrib project uses the Apache 2.0 license.

**Comment by CRC-Mismatch** [comment]
It's Apache 2.0 itself, but it's only mentioned under `composer.json`... https://github.com/CRC-Mismatch/opentelemetry-auto-redis/blob/3a3354ab53a564ec7f054b7f2256a8b417cd4c64/composer.json#L8

I'll add the according License file right away, either way!
